<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'u281242385_bbs');
define('_DB_USER_', 'u281242385_bbs');
define('_DB_PASSWD_', '123456');
define('_DB_PREFIX_', 'u281242385_bbs');
define('_MYSQL_ENGINE_', 'MyISAM');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 't4kBH4d2RcmsFQKT3j1joARO3Y4cvmSJSJnZ9PMVx5dwa3zkkL4cvE2V');
define('_COOKIE_IV_', 'OWuFjLDk');
define('_PS_CREATION_DATE_', '2014-10-30');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'WLuXn1OFixWDY16G871NqU7AbTm7r8Tu');
define('_RIJNDAEL_IV_', 'irl/PCc5X9/rdkmm4Ah1uA==');
